---
title: "Settings file"
---
The user must set the model settings in the `settings.toml` configuration file. Beyond standard settings FIAT offers the freedom to provide additional setting to have more control over FIAT (@tbl-toml). More advanced options are described in the [advanced options](../advanced.qmd) page.

### Required input
For simply running FIAT with most standard settings, the `settings.toml` configuration file can be kept rather simple (only required fields). An example for running a geometry model is given below:

```html
[output]
path = "output"

[output.csv]
name = "output.csv"

[output.geom]
name1 = "spatial.gpkg"

[hazard]
file = "hazard/SL_10yr_reprojected.tif"
crs = "EPSG:4326"
elevation_reference = "DEM"
risk = false

[exposure.geom]
file1 = "./exposure/buildings.gpkg"
crs = "EPSG:4326"

[exposure.csv]
file = "./exposure/exposure.csv"

[vulnerability]
file = "./vulnerability/vulnerability_curves.csv"

```

The fields are elaborated below:

**[output]**

`path`:  The path to the output folder in the working directory.

**[output.csv]**

`name`: The path to the output CSV file that will be created, that contains the information from the exposure.csv and the damages per asset.

**[output.geom]**

`name1`: This sets the name and location of the output vector file that contains the geometry, location and the damages per asset.

**[hazard]**

`file`: The file path to the hazard file, can be a list of files.

`crs`: The projection of the hazard file. If no global projection is defined, the output will be in the same projection as the hazard map.

`elevation_reference`: This indicates the elevation reference of the flood map. In case of a flood-depth map this should be "DEM" while in case of a flood-elevation map this should be "datum".

`risk`: In case of a risk calculation this must be set to "true", for a single events this must be set to "false".

**[exposure.geom]**

`file1`: The path to the exposure vector file (recommended to be within the [exposure folder](data.qmd)) with the assets' geometry and Object ID. The user can provide multiple vector files by creating more fields like `file2`, `file3`, etc.

`crs`: The projection of the exposure vector file(s).

**[exposure.csv]**

`file`: The path to the exposure CSV file (recommended to be within the [exposure folder](data.qmd)) that contains the [required information](exposure.qmd) per asset. There can only be one exposure CSV file.

**[vulnerability]**

`file`: The path to the vulnerability curves CSV file within the [vulnerability folder](data.qmd) that contains the [damage curves](vulnerability.qmd). Only one vulnerability curves file is allowed.

::: {.callout-note}
File paths in the settings can be relative to the settings.toml file or absolute.
:::

### Optional input
If the user prefers to have more control over their model run or to utilize grid data instead of vector data, FIAT offers the flexibility to customize settings for each variable (@tbl-toml). Advanced FIAT users can find more options in the [advanced options page](../advanced.qmd).

| Field                        | Description                                                                                                                                                                  | Required                            | Default                                                                   | Example                                   |
|------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------|---------------------------------------------------------------------------|-------------------------------------------|
| **[global]**                 |                                                                                                                                                                              |                                     |                                                                           |                                           |
| crs                          | Global projection for the model and the output. If not defined, the default crs for the model output is the same as the hazard map.                                          | No                                  | hazard map projection                                                     | 'EPSG:32617'                              |
| **[global grid]**            |                                                                                                                                                                              |                                     |                                                                           |                                           |
| chunk                        | Divide grid into smaller chunks. Define grid chunk size                                                                                                                      | No                                  |                                                                           | [1024, 1014]                              |
| **[output]**                 |                                                                                                                                                                              |                                     |                                                                           |                                           |
| path                         | Set directory path to save the output                                                                                                                                        | Yes                                 |                                                                           | 'output'                                  |
| **[output.csv]**             |                                                                                                                                                                              |                                     |                                                                           |                                           |
| name                         | File name of the output.csv file containing the exposure data incl. the damage per asset.                                                                                    | Yes                                 | 'output.csv'                                                              | 'output.csv'                              |
| **[output.geom]**            |                                                                                                                                                                              |                                     |                                                                           |                                           |
| name1                        | File name of the output vector data. Can be various spatial files. Find details about  file formats in the data documentation.                                               | Yes                                 |                                                                           | 'spatial.gpkg'                            |
| **[output.grid]**            |                                                                                                                                                                              | optional                            |                                                                           |                                           |
| name                         | File name of the output for the grid model; WARN: not fully implemented yet                                                                                                  | Yes, if working with grid           | 'output.nc'                                                               | 'output.nc'                               |
| **[hazard]**                 |                                                                                                                                                                              |                                     |                                                                           |                                           |
| file                         | Directory path to hazard file (raster or netCDF). Can contain one (for events) or multiple (for return periods) bands                                                        | Yes                                 |                                                                           | 'hazard/event_map.nc'                     |
| crs                          | Projection of hazard data                                                                                                                                                    | Yes, if crs is unknown in dataset   |                                                                           | 'EPSG:32617'                              |
| elevation_reference          | Define the elevation reference. Either Digital Elevation Model (Flood depth map) or Datum (Flood elevation map)                                                              | Yes                                 |                                                                           | 'dem'                                     |
| risk                         | Hazard input is a returning event and multiple flood maps are ingested to compute the risk. True/False If true, risk (EAD) is computed. If false, a single event is computed | Yes                                 |                                                                           | True                                      |
| return_periods               | Return periods for hazard calculation when they cannot be inferred from the data itself                                                                                      | No                                  |                                                                           | [2, 5, 10, 25]                            |
| **[hazard.settings]**        |                                                                                                                                                                              |                                     |                                                                           |                                           |
| subset                       | Specific layer from a multilayered netCDF file (GDAL can't read those properly)                                                                                              | No                                  |                                                                           | 'zs'                                      |
| var_as_band                  | True/False Read netCDF subdatasets as raster bands                                                                                                                           | No                                  |                                                                           | False                                     |
| **[exposure.geom]**          |                                                                                                                                                                              |                                     |                                                                           |                                           |
| file1                        | File path of exposure vector file with Object ID column to enable linking exposure.csv output to vector file.                                                                | Yes                                 | **buildings**: 'exposure/buildings.gpkg' **roads**: 'exposure/roads.gpkg' | 'exposure/buildings.gpkg'                 |
| crs                          | Projection of exposure data                                                                                                                                                  | Yes, if crs is unknown in dataset   |                                                                           | 'EPSG:32617'                              |
| index                        | Define the name of the index column of the data to link the exposure CSV file with the exposure vector file.                                                                 | No                                  | 'Object ID'                                                               | 'Object ID'                               |
| **[exposure.csv]**           |                                                                                                                                                                              |                                     |                                                                           |                                           |
| csv                          | File path to exposure.csv file, that contains information about e.g. asset type, max. potential damage, aggregation and so forth)                                            | Yes                                 | 'exposure/exposure.csv'                                                   | 'exposure/exposure.csv'                   |
| **[exposure.csv.settings]**  |                                                                                                                                                                              |                                     |                                                                           |                                           |
| delimiter                    | The delimiter of the CSV file, by default this is a comma (',')                                                                                                              | No                                  | ','                                                                       | ';'                                       |
| **[exposure.grid]**          |                                                                                                                                                                              |                                     |                                                                           |                                           |
| file                         | File path to exposure.nc grid file, that contains the spatial information and information about the maximum potential damage per cell.                                       | Yes, if netCDF is provided as input | 'exposure/raster.nc'                                                      | 'exposure/raster.nc'                      |
| crs                          | Output projection                                                                                                                                                            | Yes, if crs is unknown in dataset   |                                                                           | 'EPSG:32617'                              |
| **[exposure.grid.settings]** |                                                                                                                                                                              |                                     |                                                                           |                                           |
| var_as_band                  | True/False Read netCDF subdatasets as raster bands                                                                                                                           | No                                  |                                                                           | True                                      |
| **[vulnerability]**          |                                                                                                                                                                              |                                     |                                                                           |                                           |
| file                         | File path to vulnerability_curves.csv file, that contains the damage functions.                                                                                              | Yes                                 |                                                                           | 'vulnerability/ vulnerability_curves.csv' |
: Settings.toml input (required and optional fields) {#tbl-toml .striped .hover .column-page-inset-right}
