---
title: "Settings"
---
The user must set the model settings in the `settings.toml` configuration file.

Besides the necessary/ required setttings one can set:

- input in regard to the computational side of FIAT (e.g. chunking, number of threads etc),
    - see this [page](computation.qmd)
- optional/ additional input that is not necessary or more data specific,
    - see this [page](optional.qmd)

### Basic input
This section pertains to all input that is vital for running a FIAT model.

These inputs/ entries are listed in the table down below with more detailed information per entry underneath the table.

::: {.callout-note}
File paths in the settings can be relative to the settings.toml file or absolute.
:::

| Entry                          | Type    | Required | Default         |
|--------------------------------|---------|----------|-----------------|
| **[output]**                   |         |          |                 |
| [path](#output)                | string  | Yes      |                 |
| **[output.csv]**               |         |          |                 |
| [name](#output.csv)            | string  | No       | output.csv      |
| **[output.geom]**              |         |          |                 |
| [name[n]](#output.geom)        | string  | No       | spatial[n].gpkg |
| **[output.grid]**              |         |          |                 |
| [name](#output.grid)           | string  | No       | ead.nc          |
| **[hazard]**                   |         |          |                 |
| [file](#hazard)                | string  | Yes      |                 |
| [elevation_reference](#hazard) | string  | Yes      |                 |
| [risk](#hazard)                | boolean | No       | false           |
| **[exposure.geom]**            |         |          |                 |
| [file[n]](#exposure.geom)      | string  | Yes      |                 |
| **[exposure.csv]**             |         |          |                 |
| [file](#exposure.csv)          | string  | Yes      |                 |
| **[vulnerability]**            |         |          |                 |
| [file](#vulnerability)         | string  | Yes      |                 |
: Most basic settings file input {#tbl-toml .hover}

#### [output]

`path`:  The path to the output folder in the working directory.

#### [output.csv]

`name`: The path to the output CSV file that will be created, that contains the information from the exposure.csv and the damages per asset.

#### [output.geom]

`name[n]`: This sets the name and location of the output vector file that contains the geometry, location and the damages per asset.

::: {.callout-warning}
If provided, the suffix is mandatory. The suffix should match the suffix of the input geometry file for which it is set.
:::

#### [output.grid]

`name`: This sets the name and location of the output raster file that contains damages per grid cell.

#### [hazard]

`file`: The file path to the hazard file, can be a list of files.

`elevation_reference`: This indicates the elevation reference of the flood map. In case of a flood-depth map this should be "DEM" while in case of a flood-elevation map this should be "datum".

`risk`: In case of a risk calculation this must be set to "true", for a single events this must be set to "false".

#### [exposure.geom]

`file[n]`: The path to the exposure vector file (recommended to be within the [exposure folder](../data/index.qmd)) with the assets' geometry and Object ID. The user can provide multiple vector files. Therefore the '[n]' suffix, as the user can create mulitple entries for vector files (e.g. `file1`, `file2` etc.).

::: {.callout-warning}
The suffix is mandatory. So if only one file is provided, name it `file1`.
:::

#### [exposure.csv]

`file`: The path to the exposure CSV file (recommended to be within the [exposure folder](../data/index.qmd)) that contains the [required information](../data/exposure.qmd) per asset. There can only be one exposure CSV file.

#### [vulnerability]

`file`: The path to the vulnerability curves CSV file within the [vulnerability folder](../data/index.qmd) that contains the [damage curves](../data/vulnerability.qmd). Only one vulnerability curves file is allowed.

### Example

An example of settings file for running a geometry model is given below:

```toml
[output]
path = "output"

[output.csv]
name = "output.csv"

[output.geom]
name1 = "spatial.gpkg"

[hazard]
file = "hazard/SL_10yr_reprojected.tif"
elevation_reference = "DEM"
risk = false

[exposure.geom]
file1 = "./exposure/buildings.gpkg"

[exposure.csv]
file = "./exposure/exposure.csv"

[vulnerability]
file = "./vulnerability/vulnerability_curves.csv"
```
