---
title: Frequently asked questions
---

### How do I install FIAT?
Visit the [Setup guide](../setup_guide/index.qmd), which provides installation instructions for Windows.

### How do I report a bug?
You can submit a new [issue](https://github.com/Deltares/Delft-FIAT/issues/new/choose) with the *Bugs* template in the FIAT repository. You can also submit an issue regarding *Missing or bad documentation*, a *Feature request*, or you can *Ask a question*.

### How do I build a model?
You can use [HydroMT-FIAT](https://deltares.github.io/hydromt_fiat/latest) to build a FIAT model or you can follow the instructions in the [User guide](../user_guide/index.qmd).

### How do I modify parameters or calibrate my model?
You can manually change parameters (e.g., the Ground Floor Height) in your exposure data in Excel or with Python. You can also use [HydroMT-FIAT](https://deltares.github.io/hydromt_fiat/latest) for this.

### How do I request different output?
You can change the output data types in the *settings.toml* file, visit the [Settings file](../user_guide/settings/index.qmd) page for more information.

### Can I use FIAT for other hazards than flooding?
Yes! If the damage that hazard causes can be estimated in the same manner as FIAT uses for flooding, other hazard maps can be used in combination with corresponding damage functions.

### What does FIAT have to do with the car brand FIAT?
Nothing, it is an acronym for **F**lood **I**mpact **A**ssessment **T**ool.
