---
title: "Home"
---

## Getting to Know FIAT 

FIAT is a free, pyhton-based **Fast Impact Assessment Tool**, designed and continuously improved by Deltares. It is configured to run quick, consistent, and well-founded **flood damage** and **risk calculations** on the basis of flood maps, and additional inputs such as depth-damage functions, asset locations and their maximum potential damages. FIAT allows rapid assessment of the direct **economic** and **monetary impacts** to buildings, utilities, and roads for input for specified flood events and return periods. Fast impact modeling removes bottlenecks in **climate adaptation planning**, allowing for the large numbers of calculations needed to understand the effectiveness of adaptation strategies and the

FIAT works with an easy for exposed assets, consisting of information on the location, exposed value, ground floor height, and associated depth-damage function, which can be modified by the user. A simple configuration file specifies the location of depth-damage functions and flood maps, as well as return periods of flood maps if calculating risk.

Thanks to its flexible character, FIAT **integrates** with various software applications such as flood modeling or GIS software and, can be called multiple times to e.g. assess uncertainty in damage estimates, or run for numerous flood scenarios. 